name: rayoflite
description: "A new Flutter project."
publish_to: 'none' 

# version android: 1.0.0+9
version: 1.1.0+15

# version ios : 1.0.0+9 before + is actual build ios version
# version: 2.3.1+4


environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^15.2.4
  http: ^0.13.4
  flutter_tts: ^3.5.0
  flutter_native_splash: ^2.4.6
  device_preview: ^1.2.0
  http_interceptor: ^1.0.2
  shared_preferences: ^2.2.2
  dio: ^5.4.0
  calendar_date_picker2: ^2.0.1
  provider: ^6.1.1
  cached_network_image: ^3.3.1
  image_picker: ^1.2.1
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  connectivity_plus: ^7.0.0
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  permission_handler: ^11.3.1
  fl_chart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/final.png"

flutter_native_splash:
  android: true
  ios: true
  color: "#ffffff"       
  image: "assets/final.png"
  android_gravity: center
  android_12:
    image: "assets/logo.png"
    color: "#ffffff"  

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/fonts/
    - assets/app-background.jpg
    - assets/orginal_logo.png
    - assets/final.png
    - assets/red-background.png
    - assets/talk-to-light.png

  fonts:
    - family: Specimen
      fonts:
        - asset: assets/fonts/OpenSans_Condensed-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans_Condensed-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans_SemiCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
    - family: Arial
      fonts:     
        - asset: assets/fonts/LiberationSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/LiberationSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/LiberationSans-Italic.ttf
          style: italic
        - asset: assets/fonts/LiberationSans-BoldItalic.ttf
          weight: 700
          style: italic


