// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe4hrIH0B2cub-sy42Xp1K4ryid3oZh9s',
    appId: '1:579133991964:web:1c06479b8ff8a3b74603d9',
    messagingSenderId: '579133991964',
    projectId: 'ray-of-light-70f71',
    authDomain: 'ray-of-light-70f71.firebaseapp.com',
    storageBucket: 'ray-of-light-70f71.firebasestorage.app',
    measurementId: 'G-89QE2JW5EX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa5cyjp19Z4T0e06KNlowJyxc7ALy45uU',
    appId: '1:579133991964:android:7cc70aaeb6d0cd3b4603d9',
    messagingSenderId: '579133991964',
    projectId: 'ray-of-light-70f71',
    storageBucket: 'ray-of-light-70f71.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHd6VKG7N9nsQvuCP8EUMnXpQxYHEa0iE',
    appId: '1:579133991964:ios:7e0da92275a86ebd4603d9',
    messagingSenderId: '579133991964',
    projectId: 'ray-of-light-70f71',
    storageBucket: 'ray-of-light-70f71.firebasestorage.app',
    iosBundleId: 'life.rayoflight.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHd6VKG7N9nsQvuCP8EUMnXpQxYHEa0iE',
    appId: '1:579133991964:ios:17910006389b778e4603d9',
    messagingSenderId: '579133991964',
    projectId: 'ray-of-light-70f71',
    storageBucket: 'ray-of-light-70f71.firebasestorage.app',
    iosBundleId: 'com.example.rayoflite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAe4hrIH0B2cub-sy42Xp1K4ryid3oZh9s',
    appId: '1:579133991964:web:1c48f25d1c484f264603d9',
    messagingSenderId: '579133991964',
    projectId: 'ray-of-light-70f71',
    authDomain: 'ray-of-light-70f71.firebaseapp.com',
    storageBucket: 'ray-of-light-70f71.firebasestorage.app',
    measurementId: 'G-9G1KVY9DQL',
  );
}
